# Generated by Django 4.0.1 on 2022-02-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_log_scrolldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=10)),
                ('birth', models.DateTimeField(blank=True, null=True)),
                ('sex', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
    ]
