# Generated by Django 4.0.1 on 2022-02-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_view_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='View_count',
        ),
    ]
