# Generated by Django 4.0.1 on 2022-02-17 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_delete_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.IntegerField(blank=True, default=0, null=True)),
                ('ipaddr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.log')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.memberinfo')),
            ],
        ),
    ]
