# Generated by Django 4.0.1 on 2022-02-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_delete_viewcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('nv_id', models.AutoField(primary_key=True, serialize=False)),
                ('hits', models.IntegerField(blank=True, default=0, null=True)),
                ('ipaddr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.log')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.memberinfo')),
            ],
        ),
    ]
