# Generated by Django 4.0.1 on 2022-02-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_viewcount_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewCount',
        ),
    ]
