# Generated by Django 4.0.1 on 2022-02-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_n_viewcount_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='n_viewcount',
            name='like_count',
        ),
    ]
